### ISSUE TITLE
Error undefined macro method 'Union#resolve'

### ISSUE THREAD

**Issue by Xosmond** [amberframework/granite#340]
Hi the last PR introduced an error when type is a union

```crystal
expanding macro
in lib/granite/src/granite/fields.cr:168: undefined macro method 'Union#resolve'

            {% elsif type.resolve <= Array %}
                          ^~~~~~~

in src/models/game.cr:10: undefined macro method 'Union#resolve'

  field sent_code_at : Time?
```

**Comment by drujensen** [comment]
@Blacksmoke16 can you look into this?

**Comment by Blacksmoke16** [comment]
Yea, I'll take a look when I get home tonight.

**Comment by Xosmond** [comment]
> Yea, I'll take a look when I get home tonight.
> 
> In the mean time just don't use a union here. Granite makes your fields nilable by default when the `field` macro expands anyway. So defining your field as `Time?` doesn't actually do anything.

Oh i see, thanks, I will do it, I didn't know everything was nilable by default.

**Comment by Blacksmoke16** [comment]
Yea, making your type nilable here actually makes the type of the property `Union(Time | Nil | Nil)`, but it knows to strip out the extra Nil.  

By default, the return type of a field getter, e.x. `model.sent_code_at`, is nilable.  However you can use the bang version of the getter, `model.sent_code_at!`, which basically just does `.not_nil!` if you know that property is not nil; due to a DB constraint or something.

@drujensen What are your thoughts on how to fix this?  We could either raise a compile time exception so people cant do it or just strip Nil out when doing the casting.

The former would make it more clear that making a property nilable doesn't actually do anything, while the latter would be a bit more lenient.

**Comment by drujensen** [comment]
@Blacksmoke16 good question.  My gut says we should do the former. But I am wondering about your proposed scenario.  Would someone want to define a field as a union type other than Nilable?  Would that be useful?

**Comment by Blacksmoke16** [comment]
If they do I'd be interested in hearing the use case.  The underlying column can only have a single type anyway.  Yes you could store `42` in both `INT` and `TEXT` columns, but even then the type of the value is `Int32` OR `String`, it can't really be both.

**Comment by drujensen** [comment]
What about `(Int32 | Int64)`?

**Comment by drujensen** [comment]
nm, the database really dictates the type here.  I think Unions should not be allowed.
