### ISSUE TITLE
Query builder for DB specific feature?

### ISSUE THREAD

**Issue by Serdnad** [amberframework/granite#402]
In my project I currently build a query using a chain of several `where` statements, many of them included conditionally. Now, I need to modify this query to only select rows where an array column (I'm using Postgres) contains a certain element. Is it currently possible to do this using a query builder? Effectively, I'm looking for the converse of an :in operator, a sort of :has or includes, if you will.

I'm aware I could do this without a query builder, using `#all('where ?=ANY(trusted)', [user_id])` for example, where trusted is an array type such as integer[], but then I'd lose out on the convenience of the query builder and would have to convert the entire query to a single SQL statement, as far as I understand it.

If this is something that doesn't currently exist but would be welcome, I'd be willing to give it a shot and submit a PR.

**Comment by robacarp** [comment]
@Serdnad there really isn't right now. The query builder approaches SQL from the perspective of what can be queried across databases, and there isn't a pattern for including dsl segments which only apply to a specific database engine.

This general idea comes up a lot, and I can think of two ways to solve it:

1) Provide an adapter specific dsl "opener". Something like `where.pg.any_equal(user_id)` might work. This would have to be included on a per-project basis, so in addition to `require "granite"` you'd need `require "granite/pg-query-extensions"`.

1) Provide a better way to make the query builder extensible so that third party shards could extend the granite query builder to add `any_equal` or whatever other selects. This is a significant lift, but could provide some long term runway.

Either of these would require some low level tweaks to the way the query builder assembles the sql. The builder makes a lot of assumptions right now, and finding a way to render well without turning the builder into spaghetti might be a big task. Perhaps there are some other options?

**Comment by Serdnad** [comment]
I see, thanks @robocarp for taking the time to explain the philosophy behind the current state of things.

It makes sense that the project would prioritize consistency across all supported databases. Unfortunately, my own project does not benefit from this, and since I'm in need of support for this sort of query in the short term, going the proper route and implementing one of the solutions you've outlined doesn't make sense for me, personally, to undertake at the moment.

However, I took your advice and thought about other options for my particular issue quite a bit, and realized that the most general solution that would solve this specific issue, as well as potentially many other query-related, possibly database-specific issues, would be to add one more method to the query builder that allowed custom SQL, similar to #all, but would still be usable as part of a surrounding query builder. In use, this would look something like:

```
users = User.where(color: "blue")
  .where("age > 18") # == where(:age, :gt, 18)
  .where("? = ANY(trusted)", [user_id]) # currently no equivalent
```

While allowing custom SQL as part of the builder might increase the likelihood of generating invalid SQL (through additional assumptions, like you mentioned), I'd argue not much more so than #all currently allows, and the benefit would be that granite's query builder would now technically provide a baseline level of support for all types of queries, including ones that rely on database-specific features. I would also imagine providing usage examples/instructions in the docs should go a long way towards helping users use this functionality without running into issues.

**Comment by drujensen** [comment]
I would suggest we deprecate the `.all(SQL)` or treat it as an alias for `.where(SQL).all`.

**Comment by Serdnad** [comment]
Deprecating or aliasing `.all(SQL)` would make sense, given the possibility of doing `.where(SQL).select`. In fact, when I'd first started using Granite, I was surprised by `#all`'s implementation, having gotten used to using it as the start of my query builders in Rails.

However, if we did do that, I think it should be replaced by a `.raw_select(SQL)` or so, to still allow queries that involve more than just "WHERE" clauses. For example, in the same project I'm currently using `.all` to perform a JOIN, by:
```
User.all("INNER JOIN follows ON users.id = follows.user_id
  WHERE follows.followed_id = ?
  LIMIT ?
  OFFSET ?",
  [id, limit, offset]
)
```
